
import { GoogleGenAI } from "@google/genai";

export const config = {
  runtime: 'edge',
};

export default async function handler(req: Request) {
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405 });
  }

  try {
    const body = await req.json();
    const { appName, description, style, primaryColor, apiKey } = body;

    // تحديد المفتاح: الأولوية للمفتاح المرسل في الطلب، ثم مفتاح البيئة
    const effectiveApiKey = apiKey || process.env.API_KEY;

    if (!effectiveApiKey) {
      return new Response(JSON.stringify({ error: 'API Key is required. Please provide it in the request body or environment variables.' }), { status: 400 });
    }

    if (!appName || !description) {
      return new Response(JSON.stringify({ error: 'Missing required fields: appName and description are mandatory.' }), { status: 400 });
    }

    // تهيئة الذكاء الاصطناعي بالمفتاح المحدد
    const ai = new GoogleGenAI({ apiKey: effectiveApiKey });
    
    const prompt = `Professional high-quality app icon for "${appName}". 
    Purpose: ${description}. 
    Style: ${style || 'minimalist'}. 
    Primary Color: ${primaryColor || '#2563eb'}. 
    Requirements: NO TEXT, NO LETTERS, isolated on a solid background, 1024x1024 resolution, modern UI/UX design.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    const part = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
    
    if (!part || !part.inlineData) {
      // التحقق من وجود رسالة خطأ نصية (مثل رفض سياسة المحتوى)
      const textError = response.candidates?.[0]?.content?.parts.find(p => p.text)?.text;
      return new Response(JSON.stringify({ error: textError || 'No image generated by the model.' }), { status: 500 });
    }

    return new Response(JSON.stringify({
      success: true,
      imageUrl: `data:image/png;base64,${part.inlineData.data}`,
      appName: appName
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error: any) {
    console.error("Vercel API Error:", error);
    return new Response(JSON.stringify({ error: error.message || 'Internal Server Error' }), { status: 500 });
  }
}
